name: Publish

on:
  release:
    types: [created]

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v2
  #       with:
  #         node-version: 16.x
  #     - run: yarn

  bump-version:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git config --global user.email "landgrenunit@gmail.com"
      - run: git config --global user.name "landgrenunit"
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: 16.x
      - run: npm version patch
      - run: git push origin main --tags
      - uses: actions/upload-artifact@v2
        with:
          name: src
          path: ./

  publish-npm:
    needs: bump-version
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          registry-url: https://registry.npmjs.org
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.SECRET_TOKEN}}
